name: Deploy main to AWS

on:
  pull_request: 
    branches: main

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - name: Install packages and build 
        run: |
          npm ci
          npm run build --if-present
      - name: Test the build
        run: npm test
