name: Build and Test 

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - name: Install packages and build 
        run: |
          npm ci
          npm run build --if-present
      - name: Test the build
        run: npm test

      - name: Test
        run: |
          npm start &
          sleep 10 &&
          curl http://localhost:8000 &&
          npm run s-test
